CREATE TABLE [dbo].[Calendar](
	[DateKey] [int] NOT NULL,
	[CalendarDate] [datetime] NOT NULL,
	[StandardDate] [varchar](10) NULL,
	[Day] [char](2) NOT NULL,
	[DaySuffix] [varchar](4) NOT NULL,
	[DayOfWeek] [varchar](9) NOT NULL,
	[DOWInMonth] [tinyint] NOT NULL,
	[DayOfYear] [int] NOT NULL,
	[WeekOfMonth] [tinyint] NOT NULL,
	[WeekOfYear] [tinyint] NOT NULL,
	[Month] [char](2) NOT NULL,
	[MonthName] [varchar](9) NOT NULL,
	[Quarter] [varchar](1) NOT NULL,
	[QuarterName] [varchar](6) NOT NULL,
	[Year] [char](4) NOT NULL,
	[MonthYear] [varchar](10) NULL,
	[MMYYYY] [varchar](6) NULL,
	[FirstDayOfMonth] [date] NULL,
	[LastDayOfMonth] [date] NULL,
	[FirstDayOfQuarter] [date] NULL,
	[LastDayOfQuarter] [date] NULL,
	[FirstDayOfYear] [date] NULL,
	[LastDayOfYear] [date] NULL,
	[HolidayText] [varchar](100) NULL,
	[IsWeekday] [int] NULL,
	[IsWeekend] [int] NULL,
	[IsWorkDay] [int] NULL,
	[IsHoliday] [int] NULL,
	[FiscalDayOfYear] [int] NULL,
	[FiscalWeekOfYear] [tinyint] NULL,
	[FiscalMonth] [tinyint] NULL,
	[FiscalQuarter] [tinyint] NULL,
	[FiscalQuarterName] [varchar](10) NULL,
	[FiscalYear] [char](4) NULL,
	[FiscalMonthYear] [varchar](10) NULL,
	[FiscalMMYYY] [varchar](6) NULL,
	[FiscalFirstDayOfMonth] [date] NULL,
	[FiscalLastDayOfMonth] [date] NULL,
	[FiscalFirstDayOfQuarter] [date] NULL,
	[FiscalLastDayOfQuarter] [date] NULL,
	[FiscalFirstDayOfYear] [date] NULL,
	[FiscalLastDayOfYear] [date] NULL,
 CONSTRAINT [PKStageDate] PRIMARY KEY CLUSTERED 
(
	[DateKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]