CREATE TABLE [dbo].[CX_Temp_Test](
	[PracticeID] [int] NULL,
	[Practice] [varchar](50) NULL,
	[NHI] [varchar](50) NULL,
	[eth1] [varchar](50) NULL,
	[Ethnicity] [varchar](50) NULL,
	[DOB] [date] NULL,
	[PatientName] [varchar](101) NULL,
	[ProviderCode] [varchar](50) NULL,
	[CellPhone] [varchar](50) NULL,
	[HomePhone] [varchar](50) NULL,
	[Age_Qtr_End] [int] NULL,
	[AgeBand] [varchar](12) NOT NULL,
	[Last_Screen] [datetime] NULL,
	[Never_Screened] [int] NOT NULL,
	[Greater_Than_5_Years] [int] NOT NULL,
	[Greater_Than_3_Years] [int] NOT NULL,
	[Programme_Goal] [numeric](2, 2) NOT NULL,
	[CX_Numerator] [int] NOT NULL,
	[Denominator] [int] NOT NULL,
	[Mamm_Due] [int] NOT NULL,
	[CX_Status] [varchar](14) NOT NULL,
	[Complete_Status] [varchar](8) NOT NULL,
	[CMI] [nvarchar](255) NULL,
	[LOCATION_OF_LAST_SCREEN] [nvarchar](255) NULL,
	[ReportingQuarter] [tinyint] NULL,
	[PriorityGroup] [int] NOT NULL,
	[CX_Denominator_Adjustor] [decimal](5, 3) NULL
) ON [PRIMARY]