CREATE TABLE [dbo].[FundingPayment](
	[FundingStreamCode] [varchar](100) NULL,
	[FundStream] [varchar](250) NULL,
	[FundingAllocationGroup] [varchar](100) NULL,
	[AllocationCode] [varchar](30) NULL,
	[Allocation] [varchar](500) NULL,
	[Paymentid] [int] NOT NULL,
	[FundingStreamID] [int] NOT NULL,
	[FundingAllocationID] [int] NOT NULL,
	[FinancialYearID] [smallint] NOT NULL,
	[YearNo] [smallint] NOT NULL,
	[QtrNo] [tinyint] NOT NULL,
	[MonthNo] [tinyint] NOT NULL,
	[FundingStreamWeight] [decimal](10, 9) NULL,
	[FundingStreamTotal] [decimal](17, 2) NULL,
	[BaseRatio] [decimal](5, 4) NULL,
	[FundingStreamBase] [decimal](23, 6) NULL,
	[FundingStreamIncentive] [decimal](24, 6) NULL,
	[MeasureGrandTotal] [decimal](19, 4) NULL,
	[MeasureBaseTotal] [decimal](19, 4) NULL,
	[MeasureIncentiveTotal] [decimal](19, 4) NULL,
	[PracticeID] [int] NULL,
	[diseaseBurdenRatio] [decimal](10, 9) NULL,
	[PracticeMaxGrandTotal] [decimal](17, 2) NULL,
	[Numerator] [decimal](20, 4) NULL,
	[Denominator] [decimal](20, 4) NULL,
	[Performance] [decimal](5, 4) NULL,
	[MeasureTarget] [decimal](5, 4) NULL,
	[BaseTarget] [decimal](5, 4) NULL,
	[PracticeEarnedBase] [decimal](17, 2) NULL,
	[PracticeEarnedIncentive] [decimal](17, 2) NULL,
	[PracticeUnearnedTotal] [decimal](17, 2) NULL,
	[Modified_Type] [varchar](10) NULL,
	[Modified_By] [varchar](50) NOT NULL,
	[ModifiedDate] [datetime] NOT NULL,
	[QuarterlyUnearnedAvailable] [decimal](17, 2) NULL,
	[QuarterlyUnearnedAchieved] [decimal](17, 2) NULL,
	[Performance_PreviousMonth] [decimal](5, 4) NULL,
	[PracticeBaseInitialMax] [decimal](17, 2) NULL,
	[PracticeIncentiveInitialMax] [decimal](17, 2) NULL,
	[PracticeIncentiveFinalMax] [decimal](17, 2) NULL
) ON [PRIMARY]