CREATE TABLE [dbo].[IMMS_AIROnly_DemoSSRS](
	[PracticeID] [int] NULL,
	[Practice] [varchar](100) NULL,
	[Full_Name] [varchar](511) NOT NULL,
	[ProviderCode] [varchar](50) NULL,
	[Ethnicity] [varchar](255) NULL,
	[Quintile] [int] NULL,
	[Gender] [varchar](255) NULL,
	[Street] [varchar](512) NULL,
	[Suburb] [varchar](255) NULL,
	[City] [varchar](255) NULL,
	[Phone] [varchar](50) NULL,
	[Longitude_X_Coordinate] [decimal](9, 6) NULL,
	[Latitude_Y_Coordinate] [decimal](8, 6) NULL,
	[CSC_Number] [varchar](255) NULL,
	[CSC_Expiry_Date] [datetime] NULL,
	[Upcoming_6_Weeks] [int] NOT NULL,
	[Scheduled_Age_6_Weeks] [int] NOT NULL,
	[Scheduled_Age_3_Months] [int] NOT NULL,
	[Scheduled_Age_5_Months] [int] NOT NULL,
	[Upcoming_12_Months] [int] NOT NULL,
	[Scheduled_Age_12_Months] [int] NOT NULL,
	[Upcoming_15_Months] [int] NOT NULL,
	[Scheduled_Age_15_Months] [int] NOT NULL,
	[Age_6_Weeks] [datetime] NULL,
	[Age_3_Months] [datetime] NULL,
	[Age_5_Months] [datetime] NULL,
	[Age_6_Months] [datetime] NULL,
	[Milestone_Age_6_Months] [int] NOT NULL,
	[Age_8_Months] [datetime] NULL,
	[Milestone_Age_8_Months] [int] NOT NULL,
	[Numerator_8_Months] [int] NOT NULL,
	[Milestone_Age_12_Months] [int] NOT NULL,
	[Numerator_12_Months] [int] NOT NULL,
	[Age_12_Months] [datetime] NULL,
	[Age_15_Months] [datetime] NULL,
	[Age_18_Months] [datetime] NULL,
	[Milestone_Age_18_Months] [int] NOT NULL,
	[Numerator_18_Months] [int] NOT NULL,
	[Age_24_Months] [datetime] NULL,
	[Milestone_Age_24_Months] [int] NOT NULL,
	[SLM_Age_24_Months_Qtr4] [int] NOT NULL,
	[Numerator_24_Months_Qtr4] [int] NOT NULL,
	[Numerator_24_Months] [int] NOT NULL,
	[Age_54_Months] [datetime] NULL,
	[Milestone_Age_54_Months] [int] NOT NULL,
	[Numerator_54_Months] [int] NOT NULL,
	[Age_60_Months] [datetime] NULL,
	[Milestone_Age_60_Months] [int] NOT NULL,
	[Numerator_60_Months] [int] NOT NULL,
	[NHI] [varchar](255) NULL,
	[Date_of_Birth] [datetime] NULL,
	[Age_Group] [varchar](17) NOT NULL,
	[Child_Age] [varchar](11) NULL,
	[VACCCODE] [varchar](8000) NULL,
	[VaccineDescription] [varchar](8000) NULL,
	[Vaccine_Group] [varchar](18) NULL,
	[WhenImm] [date] NULL,
	[ImmunisationStatus] [varchar](80) NULL,
	[VaccineOutcome] [varchar](8000) NULL,
	[VaccineDose] [int] NULL,
	[row_NUM] [bigint] NULL,
	[DataSource] [varchar](3) NULL,
	[Due_Group] [varchar](17) NOT NULL,
	[Due_Group_24Months_Qtr4] [varchar](17) NOT NULL,
	[Patient_Unenrolled] [int] NULL,
	[NES_Source] [varchar](20) NULL,
	[Scheduled_Age_Group] [varchar](17) NOT NULL,
	[Scheduled_Age_Group_24M_Qtr4] [varchar](17) NOT NULL,
	[Due_Group_Sort] [int] NOT NULL,
	[Due_Group_Sort_24M_Qtr4] [int] NOT NULL,
	[Eligibility_Age] [datetime] NULL
) ON [PRIMARY]