CREATE TABLE [dbo].[Stage_CX_Temp_24Mar2017_ToDelete](
	[PracticeID] [int] NULL,
	[nhi] [varchar](50) NULL,
	[Firstname] [varchar](50) NULL,
	[Surname] [varchar](50) NULL,
	[DOB] [datetime] NULL,
	[eth1] [varchar](50) NULL,
	[ethnicity] [varchar](255) NULL,
	[Quintile] [int] NULL,
	[ProviderCode] [varchar](50) NULL,
	[AgeBand] [varchar](12) NOT NULL,
	[Never_Screened] [int] NOT NULL,
	[Greater_Than_5_Years] [int] NOT NULL,
	[Greater_Than_3_Years] [int] NOT NULL,
	[CMI] [nvarchar](255) NULL,
	[PMS_Outcome] [varchar](50) NULL,
	[Cohort_PracticeID] [int] NULL,
	[Cohort_PMS] [varchar](255) NULL,
	[Collect_PMS] [varchar](255) NULL,
	[LOCATION_OF_LAST_SCREEN] [nvarchar](255) NULL,
	[Age_Qtr_End] [int] NULL,
	[PMS_SourceSurgeryID] [int] NULL,
	[PMS_LastScreen] [datetime] NULL,
	[Collections_Last_Screen] [datetime] NULL,
	[Last_Screen] [datetime] NULL,
	[In_Denominator] [int] NOT NULL,
	[In_Numerator_All] [int] NOT NULL,
	[In_Numerator_Collections] [int] NOT NULL,
	[In_Numerator_PMS] [int] NOT NULL,
	[Next_Recall] [date] NULL,
	[Last_Complete_CarePlan] [date] NULL,
	[cellphone] [varchar](50) NULL,
	[Homephone] [varchar](50) NULL,
	[Mamm_Due] [int] NOT NULL,
	[CX_Status] [varchar](14) NOT NULL,
	[CX_CarePlan_Status] [varchar](17) NOT NULL,
	[CX_CarePlan_Status_sort] [int] NOT NULL,
	[PriorityGroup] [int] NOT NULL,
	[CX_Denominator_Adjustor] [decimal](5, 3) NULL
) ON [PRIMARY]