CREATE TABLE [dbo].[Stage_LINC_Reporting](
	[PracticeID] [int] NULL,
	[Practice] [varchar](100) NULL,
	[NHI] [varchar](50) NULL,
	[Surname] [varchar](50) NULL,
	[Firstname] [varchar](50) NULL,
	[Prov] [varchar](50) NULL,
	[DOB] [datetime] NULL,
	[AgeQtrEnd] [int] NULL,
	[Gender] [varchar](50) NULL,
	[Ethnicity] [varchar](100) NULL,
	[Quintile] [int] NULL,
	[CellPhone] [varchar](50) NULL,
	[HomePhone] [varchar](50) NULL,
	[CalculatedLincScore] [int] NULL,
	[CurrentRecordedLincScore] [int] NULL,
	[DAREnrolmentDate] [datetime] NULL,
	[Last_Completed] [date] NULL,
	[LINC_Next_Planned] [datetime] NULL,
	[LTCEnrolmentExpiryDate] [date] NULL,
	[In_Denominator] [int] NOT NULL,
	[In_Numerator] [int] NULL,
	[LTC_Status] [varchar](50) NOT NULL,
	[LTC_Status_Sort] [int] NOT NULL,
	[DAR_Next_Planned] [datetime] NULL,
	[DARLastExcludedDate] [datetime] NULL,
	[LTCEnrolmentIndicator] [bit] NULL,
	[LTCEnrolmentIndicator_Text] [varchar](13) NOT NULL,
	[LTCEnrolmentIndicator_Sort] [int] NOT NULL,
	[Network_Group] [varchar](7) NOT NULL,
	[RS_Referred] [varchar](3) NOT NULL,
	[RSAnnaulReviewNextPlanDate] [datetime] NULL,
	[RSAnnualReviewLastCompletedDate] [datetime] NULL,
	[RSAnnualReviewLastExcludedDate] [datetime] NULL,
	[RSEnrolmentDate] [datetime] NULL,
	[HBa1c] [decimal](6, 2) NULL,
	[Alb Creat Ratio] [varchar](500) NULL,
	[ACEi or A2] [varchar](500) NULL,
	[Diabetes Type] [varchar](500) NULL,
	[HbA1c_Bands] [varchar](13) NOT NULL,
	[HBa1c_Bands_sort] [int] NOT NULL,
	[WholeGroup] [int] NOT NULL,
	[PatientUnenrolled] [bit] NULL,
	[DiabetesIndicator] [bit] NULL
) ON [PRIMARY]