CREATE TABLE [dbo].[Stage_CVDRA_Report](
	[NHI] [varchar](50) NULL,
	[FullName] [varchar](100) NULL,
	[PracticeID] [int] NULL,
	[Provider] [varchar](100) NULL,
	[DOB] [date] NULL,
	[Age_As_At] [int] NULL,
	[Gender] [varchar](50) NULL,
	[Ethnicity1Description] [varchar](50) NULL,
	[Eth1] [int] NULL,
	[Eth2] [int] NULL,
	[Eth3] [int] NULL,
	[Quintile] [int] NULL,
	[LastScreen] [datetime] NULL,
	[ExternalToPractice] [int] NOT NULL,
	[CVDRisk] [decimal](8, 2) NULL,
	[CVDRisk_Bands] [varchar](12) NULL,
	[CVDRisk_Bands_Sort] [int] NULL,
	[Category] [varchar](50) NULL,
	[VirtualScreen] [int] NULL,
	[DIAB] [int] NULL,
	[Heart] [int] NULL,
	[Stroke] [int] NULL,
	[Vascular] [int] NULL,
	[InFundedProgramme] [int] NULL,
	[FundedScreenComplete] [bit] NULL,
	[CVDRA_Status] [varchar](20) NULL,
	[DateStamp] [datetime] NULL,
	[CellPhone] [varchar](50) NULL,
	[HomePhone] [varchar](50) NULL,
	[ProviderCode] [varchar](50) NULL,
	[EnrolledInPMS] [varchar](50) NULL,
	[CVDRisk_Text] [varchar](500) NULL,
	[PatientUnenrolled] [bit] NULL,
	[CVDRisk_Bands_2018] [varchar](12) NULL,
	[CVDRisk_Bands_Sort_2018] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Stage_CVDRA_Report] ADD  CONSTRAINT [DF_Stage_CVDRA_Report_DateStamp]  DEFAULT (getdate()) FOR [DateStamp]