CREATE TABLE [dbo].[Temp_Stage_CX_Reporting_20230703_Before](
	[PracticeID] [int] NULL,
	[nhi] [varchar](50) NULL,
	[PatientName] [varchar](100) NULL,
	[DOB] [datetime] NULL,
	[Age_Qtr_End] [int] NULL,
	[AgeBand] [varchar](12) NOT NULL,
	[ethnicity] [varchar](255) NULL,
	[Quintile] [int] NULL,
	[cellphone] [varchar](50) NULL,
	[Homephone] [varchar](50) NULL,
	[ProviderCode] [varchar](50) NULL,
	[Mamm_Due] [int] NOT NULL,
	[In_Numerator_All] [int] NOT NULL,
	[In_Denominator] [int] NOT NULL,
	[CX_Denominator_Adjustor] [decimal](5, 3) NULL,
	[CX_Status] [varchar](14) NOT NULL,
	[Next_Recall] [date] NULL,
	[Last_Complete_CarePlan] [date] NULL,
	[CX_CarePlan_Status] [varchar](35) NULL,
	[CX_CarePlan_Status_sort] [int] NOT NULL,
	[PMS_LastScreen] [datetime] NULL,
	[Collections_Last_Screen] [datetime] NULL,
	[Last_Screen] [datetime] NULL,
	[Data_Origin] [varchar](15) NULL,
	[PMS_Collections_Compare] [varchar](50) NULL,
	[PMS_Collections_Compare_Sort] [int] NULL,
	[CMI] [varchar](255) NULL,
	[Last_PMS_OutcomeCode] [varchar](50) NULL,
	[Last_Result] [varchar](255) NULL,
	[LOCATION_OF_LAST_SCREEN] [varchar](255) NULL,
	[PriorityGroup] [int] NOT NULL,
	[PatientUnenrolled] [bit] NULL
) ON [PRIMARY]