CREATE TABLE [dbo].[Temp_Financial_Data](
	[Date_Year] [smallint] NOT NULL,
	[Financial_Year] [smallint] NOT NULL,
	[Quarter_No] [tinyint] NOT NULL,
	[Month_No] [tinyint] NOT NULL,
	[Month_In_Qtr] [int] NULL,
	[Month_Name] [nvarchar](30) NULL,
	[PracticeID] [int] NOT NULL,
	[Practice] [varchar](100) NOT NULL,
	[PracticeDALY] [decimal](16, 14) NOT NULL,
	[Contract] [varchar](100) NOT NULL,
	[ContractType] [varchar](20) NOT NULL,
	[Contract_AnnualAmount] [decimal](12, 2) NOT NULL,
	[MeasureID] [int] NOT NULL,
	[measureGroup] [varchar](100) NULL,
	[MeasureCode] [varchar](20) NOT NULL,
	[MeasureFriendlyDescription] [varchar](100) NULL,
	[MeasureDescription] [varchar](250) NOT NULL,
	[ContractWeight] [decimal](10, 9) NOT NULL,
	[MeasureDALY] [decimal](16, 14) NOT NULL,
	[MeasureTarget] [decimal](3, 2) NOT NULL,
	[Performance] [decimal](3, 2) NOT NULL,
	[MeasureQuarterlyMax] [decimal](15, 5) NOT NULL,
	[MeasureMonthlyMax] [decimal](15, 5) NOT NULL,
	[ActualQuarterly] [decimal](15, 5) NOT NULL,
	[ActualMonthly] [decimal](15, 5) NOT NULL,
	[CarryOverQuarterly] [decimal](15, 5) NOT NULL,
	[CarryOverMonthly] [decimal](15, 5) NOT NULL,
	[MonthComplete] [bit] NOT NULL
) ON [PRIMARY]