CREATE TABLE [dbo].[Temp_FinancialData_PracticeReports](
	[Date_Year] [smallint] NOT NULL,
	[Financial_Year] [smallint] NOT NULL,
	[Quarter_No] [tinyint] NOT NULL,
	[Month_No] [tinyint] NOT NULL,
	[Month_Name] [nvarchar](30) NULL,
	[MonthComplete] [bit] NOT NULL,
	[Qtr_DateRange] [varchar](32) NULL,
	[PracticeID] [int] NOT NULL,
	[Practice] [varchar](100) NOT NULL,
	[PracticeDALY] [decimal](16, 14) NOT NULL,
	[MeasureGroup] [varchar](100) NULL,
	[MeasureCode] [varchar](20) NOT NULL,
	[MeasureFriendlyDescription] [varchar](100) NULL,
	[MaintenanceTarget] [decimal](3, 2) NULL,
	[IncentiveTarget] [decimal](3, 2) NULL,
	[Performance] [decimal](3, 2) NOT NULL,
	[QuarterlyMaintenanceMax] [decimal](38, 5) NULL,
	[MonthlyMaintenanceMax] [decimal](38, 5) NULL,
	[QuarterlyIncentiveMax] [decimal](38, 5) NULL,
	[MonthlyIncentiveMax] [decimal](38, 5) NULL,
	[QuarterlyMaxTotal] [decimal](38, 5) NULL,
	[MonthlyMaxTotal] [decimal](38, 5) NULL,
	[QuarterlyActualTotal] [decimal](10, 2) NULL,
	[MonthlyActualTotal] [decimal](38, 5) NULL,
	[CarryOverQtr_1_Total] [decimal](38, 5) NULL,
	[CarryOverQtr_2_Total] [decimal](38, 5) NULL,
	[CarryOverQtr_3_Total] [decimal](38, 5) NULL,
	[CarryOverQtr_4_Total] [decimal](38, 5) NULL,
	[CarryOverMonthlyTotal] [decimal](38, 5) NULL,
	[Qtr_1_Complete] [bit] NULL,
	[Qtr_2_Complete] [bit] NULL,
	[Qtr_3_Complete] [bit] NULL,
	[Qtr_4_Complete] [bit] NULL,
	[Month1_of_Qtr] [nvarchar](30) NULL,
	[Month2_of_Qtr] [nvarchar](30) NULL,
	[Month3_of_Qtr] [nvarchar](30) NULL,
	[Month_1_Of_Qtr_ActualTotal] [decimal](38, 2) NULL,
	[Month_2_Of_Qtr_ActualTotal] [decimal](38, 2) NULL,
	[Month_3_Of_Qtr_ActualTotal] [decimal](38, 2) NULL,
	[ThisQuarter_CarryOver] [decimal](38, 2) NULL,
	[Month_1_Complete] [bit] NULL,
	[Month_2_Complete] [bit] NULL,
	[Month_3_Complete] [bit] NULL,
	[GrandCarryOverQtr_Total] [decimal](38, 5) NULL
) ON [PRIMARY]